# Generated by Django 4.2 on 2023-04-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='product',
            new_name='service',
        ),
    ]
