# Generated by Django 4.2 on 2023-04-11 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Polnaya stavka', 'FT'), ('Pol stavka', 'PT')], default='Polnaya stavka', max_length=25)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
