# Generated by Django 4.2 on 2023-04-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
